language: node_js
node_js:
  - "6"
before_script:
  - npm install -g create-react-app
  - yarn
  - 
script:
  - yarn build

deploy:
  provider: pages
  local_dir: build
  repo: MarxJiao/draft-demo
  skip_cleanup: true
  github_token: $GIT
  on:
    branch: master
  target_branch: gh-pages